import { cookies } from 'next/headers'
import styles from '../dashboard.module.css'

const copy = {
  en: { eyebrow:'Revenue proof', title:'Make your numbers credible.', intro:'Connect a supported source in read-only mode.', soon:'Coming soon', cardTitle:'Revenue verification — after security review', body:'Stripe, ЮKassa, and NOWPayments connections are temporarily disabled while the security audit is completed. Manual figures remain available and always appear as Unverified.', points:['Manual revenue always says Owner entered · Unverified','Verified connections return only after the security audit','No provider credentials are collected while verification is disabled'], cta:'Connect · Coming soon', security:'Your credentials stay private.', securityBody:'When verification launches, provider credentials will be encrypted and never exposed in the browser or public profile.' },
  ru: { eyebrow:'Подтверждение выручки', title:'Сделайте цифры убедительными.', intro:'Подключите поддерживаемый источник в режиме только для чтения.', soon:'Скоро', cardTitle:'Верификация выручки — после аудита', body:'Подключения Stripe, ЮKassa и NOWPayments временно отключены до завершения аудита безопасности. Ручные цифры доступны и всегда помечены как «Не подтверждено».', points:['Ручная выручка всегда отмечена «Введено владельцем · Не подтверждено»','Подключения вернутся только после аудита безопасности','Пока верификация отключена, данные провайдеров не собираются'], cta:'Подключить · Скоро', security:'Данные останутся приватными.', securityBody:'После запуска учётные данные провайдера будут зашифрованы и никогда не попадут в браузер или публичный профиль.' },
} as const

export default async function RevenuePage() {
  const locale = (await cookies()).get('proofpage-locale')?.value === 'ru' ? 'ru' : 'en'; const t = copy[locale]
  return <main className={styles.content}><div className={styles.pageHead}><div><p className={styles.eyebrow}>{t.eyebrow}</p><h1>{t.title}</h1><p>{t.intro}</p></div></div><section className={styles.revenueHero}><div className={styles.providerLogo}>⌁</div><div><span className={styles.proBadge}>{t.soon}</span><h2>{t.cardTitle}</h2><p>{t.body}</p><ul>{t.points.map((point) => <li key={point}>○ {point}</li>)}</ul></div><button className={styles.disabledButton} disabled aria-disabled="true">{t.cta}</button></section><section className={styles.securityNote}><strong>{t.security}</strong><p>{t.securityBody}</p></section></main>
}
